apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  bgpInstances:
  - name: frr-k8s
    localASN: 65200
    peers:
    - name: "frr"
      peerASN: 65001
      peerAddress: 10.10.10.3
      peerConfigRef:
        name: "cilium-peer"
