apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: cilium
releaseName: cilium
name: cilium
namespace: kube-system
version: 1.18.4
repo: https://helm.cilium.io
includeCRDs: true
valuesInline:
  envoy:
    enabled: false
  autoDirectNodeRoutes: true
  bgpControlPlane:
    enabled: true
  ipam:
    mode: cluster-pool
    operator:
      clusterPoolIPv4PodCIDRList:
        - 192.168.0.0/22
      clusterPoolIPv4MaskSize: 24
  ipv4NativeRoutingCIDR: 192.168.0.0/22
  ipv6:
    enabled: false
  k8sServiceHost: OVERRIDE_ME
  k8sServicePort: 6443
  kubeProxyReplacement: true
  routingMode: native
